name: Update Snap on new releases of its source

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-version:
    name: Detect new releases
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo snap install yq

      - id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: open-telemetry/opentelemetry-collector-releases
          excludes: prerelease, draft

      - name: Checkout the Snap source
        uses: actions/checkout@v3
        with:
          path: main

      - id: check
        name: Check for new releases
        shell: bash
        run: |
          release=$(yq '.version' $GITHUB_WORKSPACE/main/snap/snapcraft.yaml)
          if [ "${release}" != "${{steps.latest-release.outputs.release}}" ]; then
            echo "release=${{steps.latest-release.outputs.release}}" >> $GITHUB_OUTPUT
            echo "New upstream release ${{steps.latest-release.outputs.release}} found"
          else
            echo "No new upstream release found"
          fi

      - name: Update the application version
        if: ${{ steps.check.outputs.release != '' }}
        shell: bash
        run: |
          current_release=$(yq '.version' $GITHUB_WORKSPACE/main/snap/snapcraft.yaml)
          echo "Current release:" $current_release
          
          latest_release="${{ steps.check.outputs.release }}"
          echo "Latest release:" $latest_release
          
          version="${latest_release#v}"
          echo "Replacing $current_release -> $version in snapcraft.yaml" 
          
          sed -i "s/${current_release}/${version}/g" $GITHUB_WORKSPACE/main/snap/snapcraft.yaml

      - name: Import and configure the GPG key for Noctua
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.NOCTUA_GPG_PRIVATE }}
          passphrase: ${{ secrets.NOCTUA_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create a PR
        if: ${{ steps.check.outputs.release != '' }}
        uses: peter-evans/create-pull-request@v7
        with:
          path: main
          token: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
          committer: "Noctua <webops+observability-noctua-bot@canonical.com>"
          author: "Noctua <webops+observability-noctua-bot@canonical.com>"
          commit-message: "chore(deps): bump opentelemetry-collector-ebpf-profiler version to ${{ steps.check.outputs.release }}"
          title: "Update to opentelemetry-collector-ebpf-profiler ${{ steps.check.outputs.release }}"
          body: Automated update to follow upstream [release](https://github.com/open-telemetry/opentelemetry-collector-releases/releases/tag/${{ steps.check.outputs.release }}) of opentelemetry-collector-ebpf-profiler.
          branch: "chore/bump-version-to-${{ steps.check.outputs.release }}"
          delete-branch: true
